main: io.github.zaynstir.anonymous.Anonymous
name: Anonymous
version: 1.3.3.7
author: Zaynstir
authors: [Zaynstir, Peaceyo]
api-version: 1.15

commands:
  mask:
    description: recieve an anonymous mask.